import { PrismaClient, MuscleGroup, Equipment, Difficulty } from "@prisma/client";

const prisma = new PrismaClient();

const exercises = [
  // ── CHEST ─────────────────────────────────────────────────────────────
  {
    name: "Barbell Bench Press",
    slug: "barbell-bench-press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Lie flat on the bench, grip the bar slightly wider than shoulder-width. Lower bar to mid-chest with elbows at ~45 degrees, press back up to lockout.",
    mediaUrl: "https://www.youtube.com/watch?v=rT7DgCr-3pg",
    isSystemExercise: true,
  },
  {
    name: "Incline Dumbbell Press",
    slug: "incline-dumbbell-press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Set bench to 30-45 degrees. Press dumbbells upwards over upper chest, converging slightly at top, lower under control for a deep stretch.",
    mediaUrl: "https://www.youtube.com/watch?v=8iPEnn-ltC8",
    isSystemExercise: true,
  },
  {
    name: "Flat Dumbbell Bench Press",
    slug: "flat-dumbbell-bench-press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Lie flat on bench holding dumbbells at chest level. Press dumbbells up until arms are extended, lower slowly feeling pec stretch.",
    mediaUrl: "https://www.youtube.com/watch?v=VmB1G1K7v94",
    isSystemExercise: true,
  },
  {
    name: "Incline Barbell Bench Press",
    slug: "incline-barbell-bench-press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Set bench to 30 degrees. Unrack barbell over collarbones, lower to upper chest, press explosively to full extension.",
    mediaUrl: "https://www.youtube.com/watch?v=SrqOu55lrYU",
    isSystemExercise: true,
  },
  {
    name: "Decline Barbell Bench Press",
    slug: "decline-barbell-bench-press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Secure legs on decline bench. Lower bar under control to lower pec line, press back up.",
    mediaUrl: "https://www.youtube.com/watch?v=LfyQBUKR8SE",
    isSystemExercise: true,
  },
  {
    name: "Cable Chest Fly",
    slug: "cable-chest-fly",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Set cables at chest height. Bring handles together in front with slight elbow bend, squeeze pecs hard, control the eccentric stretch.",
    mediaUrl: "https://www.youtube.com/watch?v=Iwe6AmxVf7o",
    isSystemExercise: true,
  },
  {
    name: "Low-to-High Cable Fly",
    slug: "low-to-high-cable-fly",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Set pulleys to lowest position. Pull handles upwards and inwards toward upper chest to bias the clavicular head.",
    mediaUrl: "https://www.youtube.com/watch?v=cwCLV_Nq_x4",
    isSystemExercise: true,
  },
  {
    name: "Pec Deck Machine Fly",
    slug: "pec-deck-machine-fly",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Sit upright with back flat against pad. Bring handles or pads together, squeezing pecs for 1 second at peak contraction.",
    mediaUrl: "https://www.youtube.com/watch?v=O-OnvUPbcFw",
    isSystemExercise: true,
  },
  {
    name: "Chest Dips",
    slug: "chest-dips",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.ADVANCED,
    instructions: "Grip parallel bars, lean torso forward ~30 degrees. Lower body until elbows reach 90 degrees, press up through chest.",
    mediaUrl: "https://www.youtube.com/watch?v=2z8JmcrW-As",
    isSystemExercise: true,
  },
  {
    name: "Push-Up",
    slug: "push-up",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.ABS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    instructions: "Standard plank push-up position, lower chest to floor keeping body rigid, press up cleanly through palms.",
    mediaUrl: "https://www.youtube.com/watch?v=IODxDxX7oi4",
    isSystemExercise: true,
  },

  // ── BACK ──────────────────────────────────────────────────────────────
  {
    name: "Barbell Deadlift",
    slug: "barbell-deadlift",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.GLUTES],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.ADVANCED,
    instructions: "Stand hip-width, grip bar outside knees. Keep spine neutral, hinge hips, push the floor away while pulling bar close to shins.",
    mediaUrl: "https://www.youtube.com/watch?v=op9kVnSso6Q",
    isSystemExercise: true,
  },
  {
    name: "Sumo Deadlift",
    slug: "sumo-deadlift",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.GLUTES],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.ADVANCED,
    instructions: "Wide stance with toes pointed out. Grip inside knees with upright torso, spread floor with feet to initiate pull.",
    mediaUrl: "https://www.youtube.com/watch?v=1ZxUUTmR4V8",
    isSystemExercise: true,
  },
  {
    name: "Lat Pulldown",
    slug: "lat-pulldown",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Grip wide bar, pull down to upper chest while depressing shoulder blades, control return without swinging.",
    mediaUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
    isSystemExercise: true,
  },
  {
    name: "Close-Grip Lat Pulldown",
    slug: "close-grip-lat-pulldown",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Attach V-bar handle. Pull down to upper chest while keeping chest proud, squeeze lower lats at bottom.",
    mediaUrl: "https://www.youtube.com/watch?v=lueEJGjTuPQ",
    isSystemExercise: true,
  },
  {
    name: "Barbell Bent-Over Row",
    slug: "barbell-bent-over-row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Hinge at hips to ~45 degrees, pull barbell towards lower ribcage, driving elbows past torso and squeezing scaps.",
    mediaUrl: "https://www.youtube.com/watch?v=FWJR5Ve8gkQ",
    isSystemExercise: true,
  },
  {
    name: "Pull-Up",
    slug: "pull-up",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Overhand grip slightly wider than shoulder width. Pull body up until chin clears the bar, lower under full control.",
    mediaUrl: "https://www.youtube.com/watch?v=eGo4IYlbE5g",
    isSystemExercise: true,
  },
  {
    name: "Chin-Up",
    slug: "chin-up",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    instructions: "Underhand (supinated) grip shoulder-width. Pull chest to bar emphasizing both lats and bicep flexion.",
    mediaUrl: "https://www.youtube.com/watch?v=brhRXlOhsAM",
    isSystemExercise: true,
  },
  {
    name: "Seated Cable Row",
    slug: "seated-cable-row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Sit upright, pull handle to navel keeping spine neutral, extend arms fully to stretch lats forward.",
    mediaUrl: "https://www.youtube.com/watch?v=GZbfZ033f74",
    isSystemExercise: true,
  },
  {
    name: "Single-Arm Dumbbell Row",
    slug: "single-arm-dumbbell-row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Place one knee and hand on flat bench. Row dumbbell back towards hip pocket, feeling lat contraction.",
    mediaUrl: "https://www.youtube.com/watch?v=dFzUjzfih7k",
    isSystemExercise: true,
  },
  {
    name: "T-Bar Row",
    slug: "t-bar-row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Straddle landmine or T-bar station. Pull handle toward torso keeping back flat and elbows tight.",
    mediaUrl: "https://www.youtube.com/watch?v=j3Igk5nyZE4",
    isSystemExercise: true,
  },
  {
    name: "Straight-Arm Cable Pulldown",
    slug: "straight-arm-cable-pulldown",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Standing with slight forward lean and arms straight. Sweep bar down in an arc to thighs, flexing lats.",
    mediaUrl: "https://www.youtube.com/watch?v=G9Jz_Xp_d6c",
    isSystemExercise: true,
  },
  {
    name: "Chest-Supported Machine Row",
    slug: "chest-supported-machine-row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.BICEPS],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Brace chest on pad eliminating lower back fatigue. Drive elbows back to target mid-traps and rhomboids.",
    mediaUrl: "https://www.youtube.com/watch?v=UCXxvVItLoM",
    isSystemExercise: true,
  },
  {
    name: "Barbell Shrug",
    slug: "barbell-shrug",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Hold barbell at hip height. Elevate shoulders straight up toward ears, pause for a second, lower under control.",
    mediaUrl: "https://www.youtube.com/watch?v=M2pxT8w_t0s",
    isSystemExercise: true,
  },
  {
    name: "Hyperextension (Back Extension)",
    slug: "hyperextension-back-extension",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.LEGS],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Position hips on 45-degree bench. Hinge forward at waist, extend back up to neutral spine alignment.",
    mediaUrl: "https://www.youtube.com/watch?v=ph3pddpKzzw",
    isSystemExercise: true,
  },

  // ── SHOULDERS ─────────────────────────────────────────────────────────
  {
    name: "Overhead Barbell Press",
    slug: "overhead-barbell-press",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CHEST],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Standing tall with core braced, press barbell overhead from clavicle to full lockout, head through at top.",
    mediaUrl: "https://www.youtube.com/watch?v=2yjwXTZQDDI",
    isSystemExercise: true,
  },
  {
    name: "Seated Dumbbell Shoulder Press",
    slug: "seated-dumbbell-shoulder-press",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Sit on upright bench. Press dumbbells overhead until arms are nearly straight, lower to ear level.",
    mediaUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog",
    isSystemExercise: true,
  },
  {
    name: "Arnold Press",
    slug: "arnold-press",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Start with dumbbells at chest, palms facing you. Rotate palms outward as you press overhead, reverse on descent.",
    mediaUrl: "https://www.youtube.com/watch?v=6Z15_WdXmVw",
    isSystemExercise: true,
  },
  {
    name: "Dumbbell Lateral Raise",
    slug: "dumbbell-lateral-raise",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Raise dumbbells laterally until parallel to floor, lead slightly with elbows, control the eccentric descent.",
    mediaUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
    isSystemExercise: true,
  },
  {
    name: "Cable Lateral Raise",
    slug: "cable-lateral-raise",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Set cable to wrist height behind or in front of body. Raise arm sideways providing constant tension on lateral delt.",
    mediaUrl: "https://www.youtube.com/watch?v=PPrzBWZDOhA",
    isSystemExercise: true,
  },
  {
    name: "Face Pull",
    slug: "face-pull",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Set rope at eye level, pull towards face while externally rotating shoulders, pulling knuckles back.",
    mediaUrl: "https://www.youtube.com/watch?v=rep-qVOkqgk",
    isSystemExercise: true,
  },
  {
    name: "Reverse Pec Deck Fly",
    slug: "reverse-pec-deck-fly",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Sit facing the machine pad. Pull handles back horizontally using rear deltoids, keeping elbows soft.",
    mediaUrl: "https://www.youtube.com/watch?v=5Y3hnhzQj28",
    isSystemExercise: true,
  },
  {
    name: "Dumbbell Rear Delt Fly",
    slug: "dumbbell-rear-delt-fly",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Hinge forward at waist. Raise dumbbells out to sides squeezing rear delts, avoiding trap dominance.",
    mediaUrl: "https://www.youtube.com/watch?v=ttvfGg9d76c",
    isSystemExercise: true,
  },
  {
    name: "Dumbbell Front Raise",
    slug: "dumbbell-front-raise",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Raise dumbbell in front of body to shoulder height, pause briefly, lower slowly.",
    mediaUrl: "https://www.youtube.com/watch?v=-t7fuZ0KhDA",
    isSystemExercise: true,
  },
  {
    name: "Upright Barbell Row",
    slug: "upright-barbell-row",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.BICEPS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Grip bar shoulder-width, pull bar vertically to mid-chest leading with elbows.",
    mediaUrl: "https://www.youtube.com/watch?v=amCU-ziHITM",
    isSystemExercise: true,
  },

  // ── BICEPS ────────────────────────────────────────────────────────────
  {
    name: "Barbell Bicep Curl",
    slug: "barbell-bicep-curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Standing, curl barbell with elbows pinned at sides, squeeze biceps hard at peak contraction.",
    mediaUrl: "https://www.youtube.com/watch?v=kwG2ipFRgfo",
    isSystemExercise: true,
  },
  {
    name: "EZ-Bar Curl",
    slug: "ez-bar-curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Grip undulating handles of EZ bar reducing wrist torque. Curl smoothly to upper chest.",
    mediaUrl: "https://www.youtube.com/watch?v=cdK_F0pYk3M",
    isSystemExercise: true,
  },
  {
    name: "Dumbbell Bicep Curl",
    slug: "dumbbell-bicep-curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Hold dumbbells at sides, curl upward supinating palms toward ceiling at the top of the stroke.",
    mediaUrl: "https://www.youtube.com/watch?v=sAq_ocpRh_I",
    isSystemExercise: true,
  },
  {
    name: "Dumbbell Hammer Curl",
    slug: "dumbbell-hammer-curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Palms facing each other (neutral grip), curl dumbbells upward to target brachialis and forearm flexors.",
    mediaUrl: "https://www.youtube.com/watch?v=zC3nLlEvin4",
    isSystemExercise: true,
  },
  {
    name: "Incline Dumbbell Curl",
    slug: "incline-dumbbell-curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Lie back on 45-60 degree incline bench. Allow arms to hang for full long-head stretch before curling.",
    mediaUrl: "https://www.youtube.com/watch?v=soxrZlIl35U",
    isSystemExercise: true,
  },
  {
    name: "Preacher Curl",
    slug: "preacher-curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Rest upper arms on preacher bench pad preventing momentum. Curl weight up, lower under strict control.",
    mediaUrl: "https://www.youtube.com/watch?v=fIWP-FRFNU0",
    isSystemExercise: true,
  },
  {
    name: "Concentration Curl",
    slug: "concentration-curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Sit on bench with elbow braced against inner thigh. Curl dumbbell focusing entirely on peak contraction.",
    mediaUrl: "https://www.youtube.com/watch?v=0AUGkch3tzc",
    isSystemExercise: true,
  },
  {
    name: "Cable Bicep Curl",
    slug: "cable-bicep-curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Use straight or EZ bar attached to low cable. Curl smoothly maintaining constant cable tension throughout range.",
    mediaUrl: "https://www.youtube.com/watch?v=NFzTWPDe6vA",
    isSystemExercise: true,
  },

  // ── TRICEPS ───────────────────────────────────────────────────────────
  {
    name: "Tricep Rope Pushdown",
    slug: "tricep-rope-pushdown",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Pin elbows at sides, push rope down and spread ends apart at bottom for maximal lateral head contraction.",
    mediaUrl: "https://www.youtube.com/watch?v=vB5OHsJ3EME",
    isSystemExercise: true,
  },
  {
    name: "Straight Bar Cable Pushdown",
    slug: "straight-bar-cable-pushdown",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Overhand grip on bar, drive bar down with elbows stationary, locking out triceps at bottom.",
    mediaUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU",
    isSystemExercise: true,
  },
  {
    name: "Skull Crusher",
    slug: "skull-crusher",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Lie on bench with EZ bar, bend elbows lowering bar to forehead or top of head, extend arms back to starting point.",
    mediaUrl: "https://www.youtube.com/watch?v=d_KZxkY_0cM",
    isSystemExercise: true,
  },
  {
    name: "Overhead Dumbbell Triceps Extension",
    slug: "overhead-dumbbell-triceps-extension",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Hold dumbbell overhead with both hands forming a diamond grip. Lower dumbbell behind neck, extend arms upward.",
    mediaUrl: "https://www.youtube.com/watch?v=_gsUck-7M74",
    isSystemExercise: true,
  },
  {
    name: "Overhead Cable Triceps Extension",
    slug: "overhead-cable-triceps-extension",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Face away from cable with rope behind head. Extend arms forward and overhead to stretch and contract the long head.",
    mediaUrl: "https://www.youtube.com/watch?v=1u18yJcLQUQ",
    isSystemExercise: true,
  },
  {
    name: "Close-Grip Barbell Bench Press",
    slug: "close-grip-barbell-bench-press",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Grip barbell shoulder-width on bench. Keep elbows tucked close to sides as you press to emphasize triceps.",
    mediaUrl: "https://www.youtube.com/watch?v=nEF0bv2FW94",
    isSystemExercise: true,
  },
  {
    name: "Tricep Dips",
    slug: "tricep-dips",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Support body on parallel bars with upright posture. Lower until elbows reach 90 degrees, press up to full lockout.",
    mediaUrl: "https://www.youtube.com/watch?v=dX_nSOFJBl4",
    isSystemExercise: true,
  },

  // ── LEGS (Quads & Hamstrings) ─────────────────────────────────────────
  {
    name: "Barbell Back Squat",
    slug: "barbell-back-squat",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CALVES],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Bar resting on upper traps, squat down until thighs are parallel or below, drive up through mid-foot.",
    mediaUrl: "https://www.youtube.com/watch?v=bEv6CCg2BC8",
    isSystemExercise: true,
  },
  {
    name: "Barbell Front Squat",
    slug: "barbell-front-squat",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.ABS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.ADVANCED,
    instructions: "Rest bar on anterior deltoids with elbows high. Squat deep with vertical torso, heavily targeting quadriceps.",
    mediaUrl: "https://www.youtube.com/watch?v=VfBOBHWX1D0",
    isSystemExercise: true,
  },
  {
    name: "Goblet Squat",
    slug: "goblet-squat",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.GLUTES],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Hold dumbbell or kettlebell vertically against chest. Squat between knees keeping chest high.",
    mediaUrl: "https://www.youtube.com/watch?v=MeIiIdhvXT4",
    isSystemExercise: true,
  },
  {
    name: "Leg Press",
    slug: "leg-press",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.GLUTES],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Place feet shoulder-width on sled, lower weight until knees bend to 90 degrees, press back up without locking knees.",
    mediaUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
    isSystemExercise: true,
  },
  {
    name: "Hack Squat",
    slug: "hack-squat",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.GLUTES],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Step onto hack squat sled with shoulders under pads. Squat down with back flat against pad to maximize quad recruitment.",
    mediaUrl: "https://www.youtube.com/watch?v=0tn5K9NlCfo",
    isSystemExercise: true,
  },
  {
    name: "Bulgarian Split Squat",
    slug: "bulgarian-split-squat",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.GLUTES],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Elevate rear foot on bench. Lower hips until front thigh is parallel to ground, drive through front heel.",
    mediaUrl: "https://www.youtube.com/watch?v=2C-uNgKwPLE",
    isSystemExercise: true,
  },
  {
    name: "Walking Dumbbell Lunge",
    slug: "walking-dumbbell-lunge",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CALVES],
    equipment: Equipment.DUMBBELL,
    difficulty: Difficulty.BEGINNER,
    instructions: "Step forward into a lunge, trailing knee tapping ground lightly. Push forward into next walking step.",
    mediaUrl: "https://www.youtube.com/watch?v=D7KaRcUTQeE",
    isSystemExercise: true,
  },
  {
    name: "Leg Extension",
    slug: "leg-extension",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Sit on machine with pad against shins. Extend legs to full knee extension, pause, lower with control.",
    mediaUrl: "https://www.youtube.com/watch?v=YyvSfVjQeL0",
    isSystemExercise: true,
  },
  {
    name: "Romanian Deadlift",
    slug: "romanian-deadlift",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.BACK],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Hinge at hips with soft knees, pushing hips far back until deep hamstring stretch is felt, return by squeezing glutes.",
    mediaUrl: "https://www.youtube.com/watch?v=JCXUYuzwNrM",
    isSystemExercise: true,
  },
  {
    name: "Lying Leg Curl",
    slug: "lying-leg-curl",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Lie prone with roller pad behind ankles. Curl heels toward glutes, pause, lower slowly.",
    mediaUrl: "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
    isSystemExercise: true,
  },
  {
    name: "Seated Leg Curl",
    slug: "seated-leg-curl",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Sit with pad against lower calves. Curl legs downward under seat, resisting the weight on the way up.",
    mediaUrl: "https://www.youtube.com/watch?v=Orxowest56U",
    isSystemExercise: true,
  },
  {
    name: "Good Morning",
    slug: "good-morning",
    primaryMuscle: MuscleGroup.LEGS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.BACK],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.ADVANCED,
    instructions: "Barbell across upper back. Hinge at hips pushing butt back while maintaining flat spine, return to upright.",
    mediaUrl: "https://www.youtube.com/watch?v=dEJ0FTm-CEk",
    isSystemExercise: true,
  },

  // ── GLUTES ────────────────────────────────────────────────────────────
  {
    name: "Barbell Hip Thrust",
    slug: "barbell-hip-thrust",
    primaryMuscle: MuscleGroup.GLUTES,
    secondaryMuscles: [MuscleGroup.LEGS],
    equipment: Equipment.BARBELL,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Upper back against bench, bar padded across hip crease. Drive hips up into full extension squeezing glutes at top.",
    mediaUrl: "https://www.youtube.com/watch?v=SEdqd1n0cvg",
    isSystemExercise: true,
  },
  {
    name: "Glute Bridge",
    slug: "glute-bridge",
    primaryMuscle: MuscleGroup.GLUTES,
    secondaryMuscles: [MuscleGroup.LEGS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    instructions: "Lie on floor with knees bent. Drive through heels to lift hips until thighs and torso align.",
    mediaUrl: "https://www.youtube.com/watch?v=OUgsJ8-Vigk",
    isSystemExercise: true,
  },
  {
    name: "Cable Glute Kickback",
    slug: "cable-glute-kickback",
    primaryMuscle: MuscleGroup.GLUTES,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Attach ankle strap to low cable. Kick leg back in a controlled arc squeezing upper glute.",
    mediaUrl: "https://www.youtube.com/watch?v=eYkKoc_WfD8",
    isSystemExercise: true,
  },
  {
    name: "Machine Hip Abduction",
    slug: "machine-hip-abduction",
    primaryMuscle: MuscleGroup.GLUTES,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Sit in abduction machine with pads on outer thighs. Spread legs outward against resistance, hold for 1 sec.",
    mediaUrl: "https://www.youtube.com/watch?v=G_Mqud4qWkM",
    isSystemExercise: true,
  },

  // ── CALVES ────────────────────────────────────────────────────────────
  {
    name: "Standing Calf Raise",
    slug: "standing-calf-raise",
    primaryMuscle: MuscleGroup.CALVES,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Balls of feet on platform, lower heels for deep gastrocnemius stretch, press up high onto toes.",
    mediaUrl: "https://www.youtube.com/watch?v=YMmgqO8Jo-k",
    isSystemExercise: true,
  },
  {
    name: "Seated Calf Raise",
    slug: "seated-calf-raise",
    primaryMuscle: MuscleGroup.CALVES,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Knees bent under pad to isolate the soleus muscle. Drop heels into full stretch, extend onto balls of feet.",
    mediaUrl: "https://www.youtube.com/watch?v=JbyjNymZOt0",
    isSystemExercise: true,
  },
  {
    name: "Leg Press Calf Press",
    slug: "leg-press-calf-press",
    primaryMuscle: MuscleGroup.CALVES,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Balls of feet on bottom edge of leg press platform. Press sled using only ankle flexion and extension.",
    mediaUrl: "https://www.youtube.com/watch?v=KxEYX_cuerM",
    isSystemExercise: true,
  },

  // ── ABS & CORE ────────────────────────────────────────────────────────
  {
    name: "Hanging Leg Raise",
    slug: "hanging-leg-raise",
    primaryMuscle: MuscleGroup.ABS,
    secondaryMuscles: [],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Hang from pull-up bar, raise legs straight or bent knees up to chest without swinging, curl pelvis upward.",
    mediaUrl: "https://www.youtube.com/watch?v=Pr1ieGZ5atk",
    isSystemExercise: true,
  },
  {
    name: "Captain's Chair Knee Raise",
    slug: "captains-chair-knee-raise",
    primaryMuscle: MuscleGroup.ABS,
    secondaryMuscles: [],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    instructions: "Brace forearms on tower pads. Raise knees toward chest, flexing lower abdominals at the top.",
    mediaUrl: "https://www.youtube.com/watch?v=p43qQ_u8X9g",
    isSystemExercise: true,
  },
  {
    name: "Cable Crunch",
    slug: "cable-crunch",
    primaryMuscle: MuscleGroup.ABS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Kneel with rope behind neck. Flex spine pulling elbows towards knees, contracting abs with zero hip movement.",
    mediaUrl: "https://www.youtube.com/watch?v=2fbooTXwU_c",
    isSystemExercise: true,
  },
  {
    name: "Ab Wheel Rollout",
    slug: "ab-wheel-rollout",
    primaryMuscle: MuscleGroup.ABS,
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.SHOULDERS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.ADVANCED,
    instructions: "Kneel holding wheel, roll forward keeping core tight and hips tucked, pull back using abdominals.",
    mediaUrl: "https://www.youtube.com/watch?v=rqiTPdK1c_I",
    isSystemExercise: true,
  },
  {
    name: "Plank",
    slug: "plank",
    primaryMuscle: MuscleGroup.ABS,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    instructions: "Forearms on floor, body in straight line from head to heels. Squeeze glutes and abs, hold isometric tension.",
    mediaUrl: "https://www.youtube.com/watch?v=ASdvN_XEl_c",
    isSystemExercise: true,
  },
  {
    name: "Side Plank",
    slug: "side-plank",
    primaryMuscle: MuscleGroup.ABS,
    secondaryMuscles: [],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    instructions: "Support body on one forearm with hips elevated, holding strict alignment to target lateral obliques.",
    mediaUrl: "https://www.youtube.com/watch?v=N_s9V3wKpHQ",
    isSystemExercise: true,
  },
  {
    name: "Russian Twist",
    slug: "russian-twist",
    primaryMuscle: MuscleGroup.ABS,
    secondaryMuscles: [],
    equipment: Equipment.BODYWEIGHT,
    difficulty: Difficulty.BEGINNER,
    instructions: "Sit with knees bent, lean back slightly. Rotate torso side-to-side tapping floor or holding a plate.",
    mediaUrl: "https://www.youtube.com/watch?v=wkD8rjkodUI",
    isSystemExercise: true,
  },

  // ── CARDIO ────────────────────────────────────────────────────────────
  {
    name: "Treadmill Running",
    slug: "treadmill-running",
    primaryMuscle: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.LEGS, MuscleGroup.CALVES],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Maintain upright posture, mid-foot strike, and steady breathing across intervals or steady state.",
    mediaUrl: "https://www.youtube.com/watch?v=9L2b2khySLE",
    isSystemExercise: true,
  },
  {
    name: "Incline Treadmill Walking",
    slug: "incline-treadmill-walking",
    primaryMuscle: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.CALVES, MuscleGroup.GLUTES],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Set incline between 10-15% and speed 4.5-5.5 km/h. Walk tall without holding handrails for maximum burn.",
    mediaUrl: "https://www.youtube.com/watch?v=d_kS3W5n9_A",
    isSystemExercise: true,
  },
  {
    name: "Rowing Machine",
    slug: "rowing-machine",
    primaryMuscle: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.LEGS],
    equipment: Equipment.MACHINE,
    difficulty: Difficulty.BEGINNER,
    instructions: "Drive back with legs, lean slightly, pull handle to lower ribs. Reverse smoothly in rhythm: legs, core, arms.",
    mediaUrl: "https://www.youtube.com/watch?v=H0r_ZGSymng",
    isSystemExercise: true,
  },
  {
    name: "Jump Rope Skipping",
    slug: "jump-rope-skipping",
    primaryMuscle: MuscleGroup.CARDIO,
    secondaryMuscles: [MuscleGroup.CALVES],
    equipment: Equipment.OTHER,
    difficulty: Difficulty.INTERMEDIATE,
    instructions: "Stay on balls of feet, turn rope using wrists, keep jumps low and rhythmic.",
    mediaUrl: "https://www.youtube.com/watch?v=u3zgHI8QnqE",
    isSystemExercise: true,
  },
];

async function main() {
  console.log(`Seeding ${exercises.length} comprehensive exercises with demo video links...`);

  let seededCount = 0;
  for (const ex of exercises) {
    await prisma.exercise.upsert({
      where: { slug: ex.slug },
      update: {
        name: ex.name,
        primaryMuscle: ex.primaryMuscle,
        secondaryMuscles: ex.secondaryMuscles,
        equipment: ex.equipment,
        difficulty: ex.difficulty,
        instructions: ex.instructions,
        mediaUrl: ex.mediaUrl,
        isSystemExercise: true,
      },
      create: ex,
    });
    seededCount++;
  }

  console.log(`Successfully seeded/updated ${seededCount} exercises with demo video URLs!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
